org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2
# Mod Properties
mod_version=handled.by.jgitver
maven_group=io.github.openbagtwo.lighterend
archives_base_name=lighterend
# Dependencies
fabric_version=0.134.0+1.21.8
# Optional
modmenu_version=15.0.0
jade_version=19.3.2+fabric
terrablender_version=1.21.8-6.0.0.3
