package io.github.openbagtwo.lighterend.datagen;

import io.github.openbagtwo.lighterend.misc.Wood.WoodSet;
import io.github.openbagtwo.lighterend.registries.LighterEndBlocks;
import io.github.openbagtwo.lighterend.registries.LighterEndBlocks.Material;
import io.github.openbagtwo.lighterend.registries.LighterEndEquipment;
import io.github.openbagtwo.lighterend.registries.LighterEndItems;
import io.github.openbagtwo.lighterend.registries.LighterEndMobs;
import io.github.openbagtwo.lighterend.registries.LighterEndMusicDiscs;
import io.github.openbagtwo.lighterend.registries.LighterEndTrimming;
import java.util.Arrays;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.client.data.BlockStateModelGenerator;
import net.minecraft.client.data.BlockStateModelGenerator.BlockTexturePool;
import net.minecraft.client.data.BlockStateModelGenerator.CrossType;
import net.minecraft.client.data.ItemModelGenerator;
import net.minecraft.client.data.ModelIds;
import net.minecraft.client.data.Models;
import net.minecraft.client.data.TextureMap;
import net.minecraft.client.data.TexturedModel;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.item.equipment.EquipmentAsset;
import net.minecraft.item.equipment.EquipmentAssetKeys;
import net.minecraft.item.equipment.trim.ArmorTrimAssets;
import net.minecraft.registry.RegistryKey;
import net.minecraft.util.Identifier;

public class ModelProvider extends FabricModelProvider {

  protected ModelProvider(FabricDataOutput output) {
    super(output);
  }

  @Override
  public void generateBlockStateModels(BlockStateModelGenerator blockModelGenerator) {
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.ENDER_BLOCK);
    generateMaterialModels(blockModelGenerator, LighterEndBlocks.VIOLECITE);
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.MISSING_TILE);
    for (Material jadestone : Arrays.asList(
        LighterEndBlocks.AZURE_JADESTONE,
        LighterEndBlocks.SANDY_JADESTONE,
        LighterEndBlocks.VIRID_JADESTONE
    )) {
      generateMaterialModels(blockModelGenerator, jadestone);
    }

//    blockModelGenerator.registerAxisRotated(
//        LighterEndBlocks.DRAGON_BONE_BLOCK, TexturedModel.CUBE_COLUMN
//    );

    /* Note: the below creates an (incorrect) model for the base dragon block. But because
             the (correct) model generated by the above commented-out code section is included
             in the non-generated assets folder, this one gets ignored. */
    BlockTexturePool texturePool = blockModelGenerator.registerCubeAllModelTexturePool(
        LighterEndBlocks.DRAGON_BONE_BLOCK
    );
    texturePool.stairs(LighterEndBlocks.DRAGON_BONE_STAIRS);
    texturePool.slab(LighterEndBlocks.DRAGON_BONE_SLAB);

    generateMaterialModels(blockModelGenerator, LighterEndBlocks.UMBRALITH);

    generateWoodModels(blockModelGenerator, LighterEndBlocks.TENANEA);
    blockModelGenerator.registerFlowerPotPlant(
        LighterEndBlocks.TENANEA_SAPLING,
        LighterEndBlocks.POTTED_TENANEA_SAPLING,
        CrossType.NOT_TINTED
    );
    blockModelGenerator.registerSingleton(LighterEndBlocks.TENANEA_LEAVES, TexturedModel.LEAVES);

    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.UMBRELLA_TREE_CLUSTER);
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.UMBRELLA_TREE_CLUSTER_EMPTY);
    blockModelGenerator.registerFlowerPotPlant(
        LighterEndBlocks.UMBRELLA_TREE_SAPLING,
        LighterEndBlocks.POTTED_UMBRELLA_SAPLING,
        CrossType.NOT_TINTED
    );
    generateWoodModels(blockModelGenerator, LighterEndBlocks.UMBRELLA);

    generateWoodModels(blockModelGenerator, LighterEndBlocks.LOTUS);

    blockModelGenerator.registerFlowerPotPlant(
        LighterEndBlocks.GLOWSHROOM_SAPLING,
        LighterEndBlocks.POTTED_GLOWSHROOM_SAPLING,
        CrossType.EMISSIVE_NOT_TINTED
    );
    generateWoodModels(blockModelGenerator, LighterEndBlocks.GLOWSHROOM);

    blockModelGenerator.registerTintableCrossBlockState(
        LighterEndBlocks.AGAVE_SEED,
        CrossType.NOT_TINTED
    );

    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.EMERALD_ICE);
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.FERROUS_ICE);
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.AUROUS_ICE);

    generateMaterialModels(blockModelGenerator, LighterEndBlocks.BORNITE);

    generateWoodModels(blockModelGenerator, LighterEndBlocks.DRAGON);
    blockModelGenerator.registerFlowerPotPlant(
        LighterEndBlocks.DRAGON_SAPLING,
        LighterEndBlocks.POTTED_DRAGON_SAPLING,
        CrossType.NOT_TINTED
    );
    blockModelGenerator.registerSingleton(LighterEndBlocks.DRAGON_LEAVES, TexturedModel.LEAVES);
  }

  public static void generateMaterialModels(BlockStateModelGenerator blockModelGenerator,
      Material material) {
    blockModelGenerator.registerCubeAllModelTexturePool(
            material.baseBlock).stairs(material.baseStairs).slab(material.baseSlab)
        .wall(material.baseWall);

    blockModelGenerator.registerCubeAllModelTexturePool(material.bricks)
        .stairs(material.brickStairs).slab(material.brickSlab).wall(material.brickWall);

    blockModelGenerator.registerCubeAllModelTexturePool(material.polished)
        .stairs(material.polishedStairs).slab(material.polishedSlab).wall(material.polishedWall)
        .button(material.button).pressurePlate(material.pressurePlate);

    blockModelGenerator.registerCubeAllModelTexturePool(material.tiles).stairs(material.tileStairs)
        .slab(material.tileSlab).wall(material.tileWall);

    blockModelGenerator.registerAxisRotated(material.pillar, TexturedModel.CUBE_COLUMN);
  }

  public static void generateWoodModels(
      BlockStateModelGenerator blockModelGenerator,
      WoodSet wood
  ) {
    blockModelGenerator.createLogTexturePool(wood.log).log(wood.log).wood(wood.wood);
    blockModelGenerator.createLogTexturePool(wood.strippedLog).log(wood.strippedLog)
        .wood(wood.strippedWood);
    blockModelGenerator.registerCubeAllModelTexturePool(wood.planks).stairs(wood.stairs)
        .slab(wood.slab).fence(wood.fence).fenceGate(wood.gate).button(wood.button)
        .pressurePlate(wood.pressurePlate);
    blockModelGenerator.registerDoor(wood.door);
    blockModelGenerator.registerTrapdoor(wood.trapdoor);
    blockModelGenerator.registerHangingSign(wood.strippedLog, wood.sign, wood.wallSign);
    blockModelGenerator.registerHangingSign(wood.strippedLog, wood.hangingSign,
        wood.wallHangingSign);
  }

  @Override
  public void generateItemModels(ItemModelGenerator itemModelGenerator) {
    for (Item item : Arrays.asList(
        LighterEndItems.AURORA_CRYSTAL_SHARD,
        LighterEndItems.LUMECORN_EAR,
        LighterEndItems.POPPED_LUMECORN,
        LighterEndItems.SILK,
        LighterEndItems.SILK_MATRIX,
        LighterEndItems.SILK_MOTH_NEST,
        LighterEndItems.UMBRELLA_JUICE,
        LighterEndItems.END_FISH_BUCKET,
        LighterEndItems.CUBOZOA_BUCKET,
        LighterEndItems.RAW_END_FISH,
        LighterEndItems.GLOW_BARB,
        LighterEndItems.END_LILY_LEAF,
        LighterEndItems.DRIED_END_LILY_LEAF,
        LighterEndItems.GLOWSHROOM_FUR,
        LighterEndItems.AGAVE_FUR,
        LighterEndItems.END_CREAM,
        LighterEndItems.END_POWDER,
        LighterEndItems.CRAB_CLAW,
        LighterEndItems.CRAB_MEAT,
        LighterEndItems.CRAB_CAKE,
        LighterEndItems.TOTEM_OF_TELEPORTATION,
        LighterEndItems.CRYSTALLINE_SULPHUR,
        LighterEndItems.MATCHSTICK,
        LighterEndItems.SHADOW_BERRY_SEEDS,
        LighterEndItems.SHADOW_BERRY,
        LighterEndItems.SHADOW_BERRY_COOKED,
        LighterEndItems.SHADOW_BERRY_JAM,
        LighterEndMusicDiscs.ENDSEEKER,
        LighterEndMusicDiscs.EO_DRACONA,
        LighterEndMusicDiscs.GRASPING_AT_STARS,
        LighterEndMusicDiscs.STRANGE_AND_ALIEN,
        LighterEndBlocks.CREEPING_MOSS.asItem(),
        LighterEndBlocks.UMBRELLA_FERN.asItem(),
        LighterEndBlocks.LUMECORN_SEED.asItem(),
        LighterEndBlocks.TENANEA.ladder.asItem(),
        LighterEndBlocks.TENANEA_FLOWER.asItem(),
        LighterEndBlocks.TENANEA_SAPLING.asItem(),
        LighterEndBlocks.UMBRELLA.ladder.asItem(),
        LighterEndBlocks.UMBRELLA_TREE_SAPLING.asItem(),
        LighterEndBlocks.CHARNIA_CYAN.asItem(),
        LighterEndBlocks.CHARNIA_GREEN.asItem(),
        LighterEndBlocks.CHARNIA_LIGHT_BLUE.asItem(),
        LighterEndBlocks.CHARNIA_ORANGE.asItem(),
        LighterEndBlocks.CHARNIA_PURPLE.asItem(),
        LighterEndBlocks.CHARNIA_RED.asItem(),
        LighterEndBlocks.LOTUS.ladder.asItem(),
        LighterEndBlocks.END_LILY_SEED.asItem(),
        LighterEndBlocks.END_LOTUS_STEM.asItem(),
        LighterEndBlocks.END_LOTUS_SEED.asItem(),
        LighterEndBlocks.GLOWSHROOM.ladder.asItem(),
        LighterEndBlocks.GLOWSHROOM_HYMENOPHORE.asItem(),
        LighterEndBlocks.GLOWSHROOM_SAPLING.asItem(),
        LighterEndBlocks.AGAVE_SEED.asItem(),
        LighterEndBlocks.AGAVE_BULB.asItem(),
        LighterEndBlocks.AURANT_POLYPORE.asItem(),
        LighterEndBlocks.PURPLE_POLYPORE.asItem(),
        LighterEndBlocks.END_LEVER.asItem(),
        LighterEndBlocks.OBELISK.asItem(),
        LighterEndBlocks.GOLD_CHANDELIER.asItem(),
        LighterEndBlocks.IRON_CHANDELIER.asItem(),
        LighterEndBlocks.TUBE_WORM.asItem(),
        LighterEndBlocks.NEEDLEGRASS.asItem(),
        LighterEndBlocks.MURKWEED.asItem(),
        LighterEndBlocks.DRAGON.ladder.asItem(),
        LighterEndBlocks.DRAGON_SAPLING.asItem(),
        LighterEndMobs.SILK_MOTH.spawnEgg,
        LighterEndMobs.DRAGONFLY.spawnEgg,
        LighterEndMobs.END_FISH.spawnEgg,
        LighterEndMobs.CUBOZOA.spawnEgg,
        LighterEndMobs.END_SLIME.spawnEgg,
        LighterEndMobs.MOOSHROOM.spawnEgg,
        LighterEndMobs.CHORUS_CRAB.spawnEgg
    )) {
      itemModelGenerator.register(item, Models.GENERATED);
    }

    itemModelGenerator.registerArmor(
        LighterEndEquipment.SILK_ELYTRA,
        LighterEndEquipment.SILK_MATERIAL,
        Identifier.ofVanilla("trims/items/chestplate_trim"),
        true
    );

    generateVanillaArmorTrims(itemModelGenerator);

    registerArmorTrim(
        itemModelGenerator,
        LighterEndEquipment.SILK_ELYTRA,
        LighterEndEquipment.SILK_MATERIAL,
        Identifier.ofVanilla("trims/items/chestplate_trim"),
        true
    );
  }


  /**
   * The following code is adapted from the Cinderscape mod by TerraformersMC
   * https://github.com/TerraformersMC/Cinderscapes/blob/0e9d760/common/src/main/java/com/terraformersmc/cinderscapes/data/CinderscapesModelProvider.java
   * under the terms of the GNU Lesser General Public License v3.0
   * https://github.com/TerraformersMC/Cinderscapes/blob/0e9d760/LICENSE
   */


  public static void generateVanillaArmorTrims(ItemModelGenerator itemModelGenerator) {

    registerArmorTrim(itemModelGenerator, Items.TURTLE_HELMET, EquipmentAssetKeys.TURTLE_SCUTE,
        ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.LEATHER_HELMET, EquipmentAssetKeys.LEATHER,
        ItemModelGenerator.HELMET_TRIM_ID_PREFIX, true);
    registerArmorTrim(itemModelGenerator, Items.LEATHER_CHESTPLATE, EquipmentAssetKeys.LEATHER,
        ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, true);
    registerArmorTrim(itemModelGenerator, Items.LEATHER_LEGGINGS, EquipmentAssetKeys.LEATHER,
        ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, true);
    registerArmorTrim(itemModelGenerator, Items.LEATHER_BOOTS, EquipmentAssetKeys.LEATHER,
        ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, true);
    registerArmorTrim(itemModelGenerator, Items.CHAINMAIL_HELMET, EquipmentAssetKeys.CHAINMAIL,
        ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.CHAINMAIL_CHESTPLATE, EquipmentAssetKeys.CHAINMAIL,
        ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.CHAINMAIL_LEGGINGS, EquipmentAssetKeys.CHAINMAIL,
        ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.CHAINMAIL_BOOTS, EquipmentAssetKeys.CHAINMAIL,
        ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.IRON_HELMET, EquipmentAssetKeys.IRON,
        ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.IRON_CHESTPLATE, EquipmentAssetKeys.IRON,
        ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.IRON_LEGGINGS, EquipmentAssetKeys.IRON,
        ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.IRON_BOOTS, EquipmentAssetKeys.IRON,
        ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.DIAMOND_HELMET, EquipmentAssetKeys.DIAMOND,
        ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.DIAMOND_CHESTPLATE, EquipmentAssetKeys.DIAMOND,
        ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.DIAMOND_LEGGINGS, EquipmentAssetKeys.DIAMOND,
        ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.DIAMOND_BOOTS, EquipmentAssetKeys.DIAMOND,
        ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.GOLDEN_HELMET, EquipmentAssetKeys.GOLD,
        ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.GOLDEN_CHESTPLATE, EquipmentAssetKeys.GOLD,
        ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.GOLDEN_LEGGINGS, EquipmentAssetKeys.GOLD,
        ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.GOLDEN_BOOTS, EquipmentAssetKeys.GOLD,
        ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.NETHERITE_HELMET, EquipmentAssetKeys.NETHERITE,
        ItemModelGenerator.HELMET_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.NETHERITE_CHESTPLATE, EquipmentAssetKeys.NETHERITE,
        ItemModelGenerator.CHESTPLATE_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.NETHERITE_LEGGINGS, EquipmentAssetKeys.NETHERITE,
        ItemModelGenerator.LEGGINGS_TRIM_ID_PREFIX, false);
    registerArmorTrim(itemModelGenerator, Items.NETHERITE_BOOTS, EquipmentAssetKeys.NETHERITE,
        ItemModelGenerator.BOOTS_TRIM_ID_PREFIX, false);
  }

  private static void registerArmorTrim(
      ItemModelGenerator generator,
      Item armor,
      RegistryKey<EquipmentAsset> equipmentKey,
      Identifier trimIdPrefix,
      boolean dyeable
  ) {
    Identifier armorModelId = ModelIds.getItemModelId(armor);
    Identifier armorTextures = TextureMap.getId(armor);
    Identifier armorOverlayTextures = TextureMap.getSubId(armor, "_overlay");

    var auroraTrimmer = new ItemModelGenerator.TrimMaterial(
        ArmorTrimAssets.of("aurora"),
        LighterEndTrimming.AURORA
    );

    Identifier trimmedModelId = armorModelId.withSuffixedPath(
        "_" + auroraTrimmer.assets().base().suffix() + "_trim"
    );
    Identifier trimTextureId = trimIdPrefix.withSuffixedPath(
        "_" + auroraTrimmer.assets().getAssetId(equipmentKey).suffix()
    );
    if (dyeable) {
      Models.GENERATED_THREE_LAYERS.upload(
          trimmedModelId,
          TextureMap.layered(armorTextures, armorOverlayTextures, trimTextureId),
          generator.modelCollector
      );
    } else {
      Models.GENERATED_TWO_LAYERS.upload(
          trimmedModelId,
          TextureMap.layered(armorTextures, trimTextureId),
          generator.modelCollector
      );
    }
  }
}
